# render.yaml - UPDATED FOR REACT
databases:
  - name: affiliate-form-db
    databaseName: affiliate_forms
    user: affiliate_user
    plan: starter

services:
  - type: web
    name: affiliate-form-builder
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
      - key: WEB_CONCURRENCY
        value: 2
